stages:
    - iac_sec
    - plan
    - apply




checkov_scan:
    stage: iac_sec
    environment:
        name: pre
    image: bridgecrew/checkov:latest
    script:
        - checkov --soft-fail -d .




terraform_plan:
    stage: plan
    environment:
        name: pre
    tags:
        - Azure
        # - Docker
    script: 
        - echo $TF_VAR_resource_group_name
        - terraform init #--upgrade
        - terraform plan -lock=false # -out myplan.out
    # artifacts:
    #    paths:
    #        - .terraform
    #        - myplan.out
    #        - .terraform.lock.hcl
    #        - terraform.tfstate
    #        - terraform.tfstate.backup
    allow_failure: true




terraform_apply:
    stage: apply
    environment:
        name: pre
    tags:
        - Azure
        # - Docker
    script:
        - terraform init #--upgrade
        - terraform apply --auto-approve -lock=false
    # it is best to decouple as much as possible, and these two jobs shouldn't really need each other
    #needs: 
    #    - terraform_plan
    when: manual
