apiVersion: v1
kind: PersistentVolume
metadata:
  name: repo-data-gitlab-gitaly-0
  labels:
    app: gitaly
    release: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: ""
  hostPath:
    path: "/storage/repo-data-gitlab-gitaly-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-gitlab-gitaly-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: repo-data-gitlab-gitaly-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-gitlab-redis-master-0
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: ""
  hostPath:
    path: "/storage/redis-data-gitlab-redis-master-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis
    component: master
    release: gitlab
    role: master
  name: redis-data-gitlab-redis-master-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: redis-data-gitlab-redis-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-gitlab-postgresql-0
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: ""
  hostPath:
    path: "/storage/data-gitlab-postgresql-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql
    release: gitlab
    role: master
  name: data-gitlab-postgresql-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: data-gitlab-postgresql-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: ""
  hostPath:
    path: "/storage/gitlab-minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-0.4.3
    heritage: Helm
    release: gitlab
  name: gitlab-minio
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: gitlab-minio
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-prometheus-server
  labels:
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: ""
  hostPath:
    path: "/storage/gitlab-prometheus-server"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.0.4
    component: server
    heritage: Helm
    release: gitlab
  name: gitlab-prometheus-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: gitlab-prometheus-server