# helm install gitlab gitlab/gitlab -f mi-gitlab/values.yaml --timeout 600s --wait --namespace gitlab
global:
  edition: ce
  email:
    enabled: false
  # smtpSettings:
  #   enabled: false 
  hosts:
    domain: gitlab.local
    # externalIP: 196.168.49.2
    https: true
  ingress:
    # enabled: true
    tls:
      enabled: true
      secretName: gitlab-tls-cert
    configureCertmanager: false
    class: "nginx"
  rails:
    bootsnap:
      enabled: false
  shell:
    port: 32022

gitlab-runner:
  runners:
    privileged: true
  certsSecretName: gitlab-gitlab-local-cert

gitlab:
  persistence:
    enabled: true
  # ingress:
  #   enabled: false
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  # initialRootPassword: "passw0rd."
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    # Map gitlab-shell to a high-numbered NodePort to support cloning over SSH since
    # Minikube takes port 22.
    service:
      type: NodePort
      nodePort: 32022
  gitaly:
    persistence:
      volumeName: repo-data-gitlab-gitaly-0

postgresql:
  persistence:
    volumeName: data-gitlab-postgresql-0

minio:
  persistence:
    volumeName: gitlab-minio

redis:
  master:
    persistence:
      volumeName: data-gitlab-postgresql-0

prometheus:
  persistence:
    volumeName: gitlab-prometheus-server

certmanager:
  install: false

certmanager-issuer:
  email: false

nginx-ingress:
  enabled: false

registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
